import { StyleSheet } from "react-native";

const profileStyle = StyleSheet.create({
  profile: {
    padding: 5,
    flex: 1,
  },
  containerViewIcons: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#3A6EA5",
    padding: 10,
    gap: 30,
  },
  icons: {
    color: "orange",
    fontSize: 25,
    fontWeight: "900",
  },
  textProfile: {
    color: "#e0e1dd",
    fontSize: 25,
    fontWeight: "500",
    textAlign: "center",
  },
  buttonTitle: {
    backgroundColor: "#e0e1dd",
    width: 60,
    alignItems: "center",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "white",
  },
  textButtonTitle: {
    color: "#3A6EA5",
    fontSize: 15,
    padding: 5,
    fontWeight: "600",
  },
  images: {
    width: "100%",
    height: 200,
    position: "relative",
  },
  cover: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  profilePic: {
    width: 180,
    height: 180,
    borderRadius: 90,
    objectFit: "cover",
    position: "absolute",
    alignSelf: "center",
    top: 100,
    zIndex: 999,
  },
  // profileContainer: {
  //   margin: 5,
  //   backgroundColor: "red",
  //   display: "flex",
  //   flexDirection: "row",
  // },
  userInfo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 110,
    margin: 5,
    flexDirection: "row",
    backgroundColor: "white",
    padding: 5,
    borderRadius: 10,
  },
  left: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
    gap: 5,
    height: 100,
  },
  iconLR: {
    fontSize: 24,
    color: "#3A6EA5",
  },
  center: {
    flex: 2,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
    gap: 3,
    height: 110,
    backgroundColor: "#3A6EA5",
    paddingBottom: 5,
  },
  iconCenter: {
    fontSize: 15,
    color: "orange",
  },
  iconTextCenter: {
    fontSize: 14,
    fontWeight: "500",
    color: "#EBEBEB",
  },
  item: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    padding: 5,
    gap: 3,
  },
  right: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 100,
    padding: 5,
  },
});

export default profileStyle;
